### ISSUE TITLE
Enhancement: Consider supporting UUIDv7 and/or ULID

### ISSUE THREAD

**Issue by cofin** [jolt-org/advanced-alchemy#25]
### Summary

Determine if adding a ULID data type is feasible at this point.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/jolt-org/advanced-alchemy/issues/25">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/25/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/jolt-org/advanced-alchemy/issues/25/pledge.svg">
</picture>
</a>

**Comment by halms** [comment]
Maybe you want to also/instead consider the newly proposed UUIDv7.
There is a [RFC draft](https://datatracker.ietf.org/doc/draft-ietf-uuidrev-rfc4122bis/) (already rather close to acceptance) that standardizes these.

Should be very similar to ULID, except for the 6 bits that are reserved for UUID version and variant and therefore 74 random bits instead of 80.
